export const CST = {
  ABILITIES: {
    MAGE: {
      FIREBALL: {
        TEXTURE_KEY: 'ABILITY_MAGE_FIREBALL',
        ANIMATION_KEY: 'ABILITY_MAGE_FIREBALL_ANIMS',
      },
    },
  },
  SCENES: {
    MENU: {
      LOAD: 'MENU_LOAD',
      ENTRY: 'MENU_ENTRY',
      MAIN: 'MENU_MAIN',
      CHARACTER: 'MENU_CHARACTER',
      STAGES: 'MENU_STAGES',
      MAP: 'MAP',
      MAP_SCUFFED: 'MAP_SCUFFED',
    },
    STAGES: {
      LOAD: 'STAGE_LOAD',
      TEST: 'STAGE_TEST',
      FIELD: 'STAGE_FIELD',
      STONEHENGE: 'STAGE_STONEHENGE',
    },
    INTERFACE: 'INTERFACE',
    INPUT: 'INPUT_SCENE',
  },
  IMAGE: {
    MENU: {
      ENTRY_BG: 'IMG_MENU_ENTRY_BG',
      MAIN_BG: 'IMG_MENU_MAIN_BG',
      LOGO: 'IMG_MENU_LOGO',
      BTN_PLAY: 'IMG_MENU_BUTTON_PLAY',
      BTN_OPTIONS: 'IMG_MENU_BUTTON_OPTIONS',
      PLAYERS_CONTROLLER: 'IMG_MENU_PLAYERS_CONTROLLER',
      PLAYERS_KEYBOARD: 'IMG_MENU_PLAYERS_KEYBOARD',
    },
    STAGES: {
      TEST: {
        BACKGROUND: 'IMG_STAGE_TEST_BG',
        FLOOR: 'IMG_STAGE_TEST_FLOOR',
      },
      FIELD: {
        BG: 'IMG_STAGE_FIELD_BG',
        FG: 'IMG_STAGE_FIELD_FG',
        COLL_GRASS: 'IMG_STAGE_FIELD_COLL_GRASS',
        COLL_PLANE: 'IMG_STAGE_FIELD_COLL_PLANE',
      },
      STONEHENGE: {
        FG: 'IMG_STAGE_STONEHENGE_FG',
        BG1: 'IMG_STAGE_STONEHENGE_BG1',
        BG2: 'IMG_STAGE_STONEHENGE_BG2',
        BG3: 'IMG_STAGE_STONEHENGE_BG3',
        RAIN: 'IMG_STAGE_STONEHENGE_RAIN',
      },
    },
    UI: {
      INGAME: {
        TIMER: 'IMG_UI_TIMER',
        CHARACTER_INFO: 'IMG_UI_CHARACTER_INFO',
        ARROW_RIGHT: 'IMG_UI_ARROW_RIGHT',
      },
      MENU: {
        BUTTON_BIG: 'IMG_UI_BUTTON_BIG',
        BUTTON_OPTIONS: 'IMG_UI_BUTTON_OPTIONS',
        MENU_BAR: 'IMG_MENU_BAR',
        MENU_SELECTED: 'IMG_MENU_SELECTED',
        MENU_ITEM: 'IMG_MENU_ITEM',
        BACK: 'BACK',
        READY: 'READY',
      },
    },
    CHARACTER: {
      MAGE: {
        PORTRAIT: 'IMG_CHARACTER_PORTAIT_MAGE',
      },
    },
  },
  TEXT: {
    UI: {
      INGAME: {
        TIMER: 'TEXT_UI_TIMER',
      },
    },
  },
  SPRITESHEET: {
    CHARACTERS: {
      TEST: 'SPR_CHARACTER_TEST',
      MAGE: 'SPR_CHARACTER_MAGE',
    },
  },
}
